// angular/my-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  
  value = '';

  onKey(event: any) {
    console.log(event.target.value);
    this.value = event.target.value;
  }
}

<input (keyup)="onKey($event)">

<br>

<welcome-aboard-html-import name={{value}}></welcome-aboard-html-import>

// react/my-app/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {

  constructor(props) {
    super(props);
    this.handleName = this.handleName.bind(this);
    this.state = {
      name: ""
    }
  }

  handleName(e) {
    this.setState({
     name: e.target.value
    });
  }

  render() {
    return (
      <div className="App">
        <input onChange={this.handleName} />
        <br />
        <welcome-aboard-html-import name={this.state.name}></welcome-aboard-html-import>
      </div>
    );
  }
}

export default App;
